FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
  cmake \
  curl \
  g++ \
  pkg-config \
  git \
  vim-common \
  libwebsockets-dev \
  libjson-c-dev \
  libssl-dev \
  sudo \
  systemd \
  software-properties-common \
&& rm -rf /var/lib/apt/lists/*

RUN apt-add-repository --yes --update ppa:ansible/ansible && \
  apt -y install ansible && \
  ansible-galaxy collection install ibm.cloudcollection
RUN curl -sL https://ibm.biz/idt-installer | bash
RUN curl -L -O https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz && \
  tar -xvf oc.tar.gz && \
  mv oc /usr/local/bin && \
  rm oc.tar.gz
RUN git clone https://github.com/tsl0922/ttyd.git
RUN cd ttyd && mkdir build && cd build && cmake .. && make && make install
EXPOSE 7681

CMD ["ttyd", "-p", "7681", "bash"]
